[tasks.build]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-uefi"]

[tasks.mkdirs]
command = "mkdir"
args = ["-p", "esp/efi/boot"]

[tasks.copyefi]
command = "cp"
args = ["-r", "target/x86_64-unknown-uefi/debug/kaypro-uefi.efi", "esp/efi/boot/bootx64.efi"]

[tasks.runqemu]
command = "qemu-system-x86_64"
args = ["-enable-kvm", "-drive", "if=pflash,format=raw,readonly=on,file=OVMF_CODE.4m.fd", "-drive", "if=pflash,format=raw,readonly=on,file=OVMF_VARS.4m.fd", "-drive", "format=raw,file=fat:rw:esp"]

[tasks.run]
dependencies = [
    "build",
    "mkdirs",
    "copyefi",
    "runqemu",
]

[tasks.default]
dependencies = [
    "run"
]
